### ISSUE TITLE
`patchState` TypeScript v5.4 compilation error

### ISSUE THREAD

**Issue by jits** [ngrx/platform#4279]
### Which @ngrx/* package(s) are the source of the bug?

signals

### Minimal reproduction of the bug/regression with instructions

https://stackblitz.com/edit/stackblitz-starters-weemkm?file=src%2Fmain.ts

If you chain multiple updaters in `patchState`, with one being an updater from the `@ngrx/signals/entities` package, you now get a compilation error when upgrading to TypeScript v5.4.3:

```ts
type CoreState = { loading: boolean };
type Entity = { id: string };

const Store = signalStore(
  withState<CoreState>({ loading: true }),
  withEntities<Entity>(),
  withMethods((store) => {
    const setLoading = () => {
      const newState: CoreState = { loading: true };
      patchState(store, newState, removeAllEntities());
    };

    return {};
  })
);
```

```
✘ [ERROR] TS2345: Argument of type 'CoreState' is not assignable to parameter of type 'PartialStateUpdater<EntityState<any>> | Partial<EntityState<any>>'. [plugin angular-compiler]

    src/main.ts:20:24:
      20 │       patchState(store, newState, removeAllEntities());
```

This previously worked fine in TypeScript v5.3.

### Expected behavior

To compile (and work) fine.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx Signals: v17.1.1
Angular: v17.3.0
TypeScript: v5.4.3

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by jits** [comment]
Looking at the TypeScript v5.4 release notes, I suspect it's the ["More Aggressive Reduction of Intersections Between Type Variables and Primitive Types"](https://devblogs.microsoft.com/typescript/announcing-typescript-5-4/#more-aggressive-reduction-of-intersections-between-type-variables-and-primitive-types) change that's causing this compilation error.

The updaters are defined with an intersection type:

https://github.com/ngrx/platform/blob/19969bd327903b2f5875794f46802f336ed1ae01/modules/signals/src/patch-state.ts#L9

(I've not had the time to dig into this just yet — posting this now in case it's useful to anyone else looking).

**Comment by SerkanSipahi** [comment]
I can confirm the issue. The error appears after moving from TypeScript v.5.3.x to v.5.4.x while upgrading to Angular v17.3.x

This worked in TS v5.3:

```ts
patchState(store, removeEntity(id, { collection }), {
   selectedLoaderId: '',
});
```

now it produces the following error:
```bash
TS2353: Object literal may only specify known properties, and selectedLoaderId does not exist in type
```

a workaround is running the patchState(s) separately:

```
patchState(store, { selectedLoaderId: '' });
patchState(store, removeEntity(id, { collection }));
```

**Comment by brandonroberts** [comment]
The fix has been released with NgRx 17.2.0
