### ISSUE TITLE
Router NavigationError for lazy-loaded routes after upgrade from NgRx 4 to 5

### ISSUE THREAD

**Issue by mflorence99** [ngrx/platform#854]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
I upgraded effects, router-store and store to `^5` from `^4`. I took note of the one breaking change that affected my code and corrected it. That is the removal of the deprecated `toPayload` function which I replaced with:

```ts
map((action: any) => action.payload)
```

I made no other changes to code that worked correctly under NgRx 4.

Now whenever I navigate to a lazy-loaded component a NavigationError occurs. Navigation to normal components is unaffected. Navigation is triggered by a direct call to `Router`:

```ts
this.routerService.navigate('/lazy');
``` 

The stacktrace is as follows:

```
ERROR Error: Uncaught (in promise): TypeError: __webpack_require__.e is not a function
TypeError: __webpack_require__.e is not a function
    at webpackAsyncContext (eval at ./client/$$_lazy_route_resource lazy recursive (main.bundle.js:6), <anonymous>:43:29)
    at SystemJsNgModuleLoader.loadAndCompile (core.js:6558)
    at SystemJsNgModuleLoader.load (core.js:6542)
    at RouterConfigLoader.loadModuleFactory (router.js:4543)
    at RouterConfigLoader.load (router.js:4523)
    at MergeMapSubscriber.eval [as project] (router.js:2015)
    at MergeMapSubscriber._tryNext (mergeMap.js:128)
    at MergeMapSubscriber._next (mergeMap.js:118)
    at MergeMapSubscriber.Subscriber.next (Subscriber.js:92)
    at ScalarObservable._subscribe (ScalarObservable.js:51)
    at webpackAsyncContext (eval at ./client/$$_lazy_route_resource lazy recursive (main.bundle.js:6), <anonymous>:43:29)
    at SystemJsNgModuleLoader.loadAndCompile (core.js:6558)
    at SystemJsNgModuleLoader.load (core.js:6542)
    at RouterConfigLoader.loadModuleFactory (router.js:4543)
    at RouterConfigLoader.load (router.js:4523)
    at MergeMapSubscriber.eval [as project] (router.js:2015)
    at MergeMapSubscriber._tryNext (mergeMap.js:128)
    at MergeMapSubscriber._next (mergeMap.js:118)
    at MergeMapSubscriber.Subscriber.next (Subscriber.js:92)
    at ScalarObservable._subscribe (ScalarObservable.js:51)
    at resolvePromise (zone.js:809)
    at resolvePromise (zone.js:775)
    at eval (zone.js:858)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4740)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
    at ZoneTask.invokeTask [as invoke] (zone.js:500)
    at invokeTask (zone.js:1517)
```

## Expected behavior:
From the docs, I did not expect to have to make any additional code changes for NgRx 5.

## Minimal reproduction of the problem with instructions:
Working on plunkr, assuming I have not made an obvious blunder!

## Version of affected browser(s),operating system(s), npm, node and ngrx:
* npm 5.6.0
* node v8.9.4
* ngrx/effects 5.1.0
* ngrx/router-store 5.0.1
* ngrx/store 5.1.0
* angular/cli 1.7.1
* angular/core 5.2.6

**Comment by MattiJarvinen-BA** [comment]
FYI fork https://stackblitz.com/edit/ngrx-router-reducer?file=app%2Fapp.module.ts and you might get reproduction done faster.

**Comment by mflorence99** [comment]
Many thanks @MattiJarvinen-BA for your help. I was unable to work on a plunkr repro this week. But today I deleted my `npm_modules` -- again -- for a clean install. I no longer see the trouble I reported and I will close this issue.

But there were two I'll record just in case they're relevant in some future case:

* Angular changed from 5.2.6 to 5.2.7
* I addressed a problem with angular/flex-layout: https://github.com/angular/flex-layout/issues/494#issuecomment-342891068

The latter forced a fixed version:

```
    "@angular/flex-layout": "2.0.0-beta.12",
```

Hard to see that it is connected to ngrx, but ngrx is mentioned by several of the commenters to the flex-layout issue.
