### PR TITLE
WIP! Typescript 5.4

### LINKED ISSUE #4279: `patchState` TypeScript v5.4 compilation error
### Which @ngrx/* package(s) are the source of the bug?

signals

### Minimal reproduction of the bug/regression with instructions

https://stackblitz.com/edit/stackblitz-starters-weemkm?file=src%2Fmain.ts

If you chain multiple updaters in `patchState`, with one being an updater from the `@ngrx/signals/entities` package, you now get a compilation error when upgrading to TypeScript v5.4.3:

```ts
type CoreState = { loading: boolean };
type Entity = { id: string };

const Store = signalStore(
  withState<CoreState>({ loading: true }),
  withEntities<Entity>(),
  withMethods((store) => {
    const setLoading = () => {
      const newState: CoreState = { loading: true };
      patchState(store, newState, removeAllEntities());
    };

    return {};
  })
);
```

```
✘ [ERROR] TS2345: Argument of type 'CoreState' is not assignable to parameter of type 'PartialStateUpdater<EntityState<any>> | Partial<EntityState<any>>'. [plugin angular-compiler]

    src/main.ts:20:24:
      20 │       patchState(store, newState, removeAllEntities());
```

This previously worked fine in TypeScript v5.3.

### Expected behavior

To compile (and work) fine.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx Signals: v17.1.1
Angular: v17.3.0
TypeScript: v5.4.3

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by jits**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

This is a first step in upgrading to TypeScript 5.4. In particular, to fix the compilation issue mentioned in #4279.

One of the existing signals entities test cases already exhibits this compilation error (the one where it combines updates two different entity states in one store). I've also added a failing test case for combining updates to entity state and regular state.

I've not had any joy in actually solving this compilation issue but will keep digging to find a solution; am putting this PR out there in case anyone else has a solution (or wants to have a go).

Note: I'm not sure if this is the best way to upgrade the TypeScript version (I essentially just bumped the version in `package.json`)? Maybe it's better to do it as part of an Nx upgrade? In any case, I'm happy to rewrite / redo this PR with better advice.

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #4279

Currently, NgRx Signals (in particular, entities) has a compilation issue with TypeScript 5.4, likely due to breaking changes in this series of TypeScript.

## What is the new behavior?

NgRx works fully with TypeScript 5.4.

## Does this PR introduce a breaking change?

(not sure yet — will depend on what actual fix(es) we put in place)

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by jits** [comment]
Closing in favour of https://github.com/ngrx/platform/pull/4290 🙌🏽
