### ISSUE TITLE
ngrx router-store selectRouteParams returns empty.

### ISSUE THREAD

**Issue by adamgen** [ngrx/platform#2511]
## Minimal reproduction of the bug/regression with instructions:

After installing angular, ngrx & router-store.

Add a router with an `:id` and use this component:

```
import { Store, createFeatureSelector, select } from '@ngrx/store';
import { Component, OnInit } from '@angular/core';
import * as fromRouter from '@ngrx/router-store';
import { tap, filter, map } from 'rxjs/operators';
import { ActivatedRoute, Router, RoutesRecognized } from '@angular/router';

export const selectRouter = createFeatureSelector<any, fromRouter.RouterReducerState<any>>('router');

export const {
  selectCurrentRoute,   // select the current route
  selectQueryParams,    // select the current route query params
  selectQueryParam,     // factory function to select a query param
  selectRouteParams,    // select the current route params
  selectRouteParam,     // factory function to select a route param
  selectRouteData,      // select the current route data
  selectUrl,            // select the current url
} = fromRouter.getSelectors(selectRouter);


@Component({
  selector: 'app-root',
  template: `
<pre>
Url params from NGRX: {{paramsFromNGRX$ | async | json}} <br>
Url params from Router: {{paramsFromRouter$ | async | json}} <br>
</pre>
`, // Outputs "Url param is:"
  styles: ['']
})
export class AppComponent implements OnInit {
  title = 'angular-examples';
  paramsFromNGRX$;
  paramsFromRouter$;
  constructor(
    private store: Store,
    private router: Router,
  ) {
  }

  ngOnInit() {
    this.paramsFromNGRX$ = this.store.pipe(
      select(selectRouteParams),
      tap(fromPipeTap => console.log({ fromPipeTap })), // logs undefined
    );

    this.paramsFromRouter$ = this.router.events
      .pipe(
        filter<RoutesRecognized>(event => event instanceof RoutesRecognized),
        map(event => event.state.root.firstChild.params),
        tap(fromRouter => console.log(fromRouter)),
      );

  }
}

```

## Expected behavior:

See the same output for `this.paramsFromNGRX$` and for `this.paramsFromRouter$`.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

The issue happened while I was on angular 9.1.1 but I upgraded to see if it's version related.

```
  "dependencies": {
    "@angular/animations": "9.1.4",
    "@angular/common": "9.1.4",
    "@angular/compiler": "9.1.4",
    "@angular/core": "9.1.4",
    "@angular/forms": "9.1.4",
    "@angular/platform-browser": "9.1.4",
    "@angular/platform-browser-dynamic": "9.1.4",
    "@angular/router": "9.1.4",
    "@ngrx/effects": "^9.1.1",
    "@ngrx/router-store": "^9.1.1",
    "@ngrx/store": "^9.1.1",
    "core-js": "3.6.4",
    "rxjs": "6.5.4",
    "tslib": "1.11.1",
    "zone.js": "0.10.3"
  },
```

## Other information:

None.

## I would be willing to submit a PR to fix this issue

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by Simon-TheHelpfulCat** [comment]
I have a similar issue.  In my case it is selectRouteParam that is causing an error.  Using 9.1.0 everything is fine, after updating to 9.1.1 I am getting a compilation error. My example has
```Typescript
export const selectRouter = createFeatureSelector<RouterReducerState<MinimalRouterStateSnapshot>>(
  DEFAULT_ROUTER_FEATURENAME
);

export const {
  selectQueryParams,
  selectQueryParam,
  selectRouteParams,
  selectRouteParam,
  selectRouteData,
  selectUrl
} = getSelectors(selectRouter);

export const selectPath = selectRouteParam('path');
```
in the app reducers and in an @ngrx/data ```EntityCollectionService``` I have

```Typescript
  private readonly selectCurrent = createSelector(
    this.selectors.selectEntities,
    selectPath,
    (entities, path) => entities.find(x => x.path === path) || null
```
When I use 9.1.1 I get this error
```
ERROR in src/app/data/entity/entity.service.ts:21:38 - error TS2367: This condition will always return 'false' since the types 'string' and 'MemoizedSelector<object, string | undefined, DefaultProjectorFn<string | undefined>>' have no overlap.

21     (entities, path) => entities.find(x => x.path === path) || null
                                              ~~~~~~~~~~~~~~~
```
When I use 9.1.0, the type of path is ```string | undefined``.

I'm pretty sure that this must have the same root cause as the example given above.

**Comment by adamgen** [comment]
I spent hours and hours only to find out that I should register the router reducer 🤦🏼‍♂️. This solves it:

```
    StoreModule.forRoot({
      router: routerReducer,
    }, {}),
```

I'm also updating the stackblitz and closing the issue in case anyone need a fully functional example.

**Comment by Simon-TheHelpfulCat** [comment]
My problem is obviously a different issue then.  I'll raise a separate issue.
