### ISSUE TITLE
Property 'pipe' does not exist on type 'Actions<Action>'.

### ISSUE THREAD

**Issue by gregkopp** [ngrx/platform#990]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

After upgrading RxJs to 6.0.0-rc, all effects are showing the same compile error:

Property 'pipe' does not exist in type 'Actions<Action>'
## Expected behavior:

No errors.

## Other information:

I am looking at upgrading out project to RxJs 6. Going through the code, I have made all changes that were having compile issues. However, every single Effect I have is showing the same error. Prior to RxJs 6 (up to and including 5.5.10), all worked as expected.

```typescript
import { Injectable } from '@angular/core';
import { Actions, Effect } from '@ngrx/effects';
import { ofAction } from 'ngrx-actions';
import { of } from 'rxjs';
import { catchError, map, mergeMap } from 'rxjs/operators';

import { WidgetSearchResult } from '../models/widget-search-result.interface';
import { WidgetSearchService } from '../services/widget-search.service';

import { OnWidgetDataRequested } from './models/on-widget-data-requested.interface';
import { WidgetSearchActions } from './widget-search.actions';

@Injectable()
export class WidgetSearchEffects {
    @Effect()
    detectWidgetDataRequested$ = this.actions$.pipe(
        ofAction(OnWidgetDataRequested),
        mergeMap((action: OnWidgetDataRequested) => this.widgetSearchService.searchById(action.payload)
          .pipe(map((data: WidgetSearchResult) => RepSearchActions.onWidgetDataReceipt(data)))),
        catchError(error => this.onError(error))
    );

    constructor(
        private actions$: Actions,
        private widgetSearchService: WidgetSearchService
    ) {}

    private onError = (error: Error) => {
        return of(WidgetSearchActions.serverError(error));
    }
}
```

I get the same error on every effect:

```
Property 'pipe' does not exist on type 'Actions<Action>'.
```

Any ideas of where I went wrong or is this a compatibility issue with ngrx-actions and RxJs 6

**Comment by brandonroberts** [comment]
[ngrx-actions](https://github.com/amcdnl/ngrx-actions) is a separate library, so the issue should be filed there.

**Comment by gregkopp** [comment]
Wow. Seems like you didn't even bother looking at this code at all. Just dismissed it as someone else's problem with no explanation.

Considering the problem is appearing here:

```
@Injectable()
export class WidgetSearchEffects {
    @Effect()
    detectWidgetDataRequested$ = this.actions$.pipe(
```

before it even gets to any ngrx-actions code. Tell me why this problem is in ngrx-actions and not @ngrx/effects? I was looking for help, not condescension.

What a jerk move.

**Comment by brandonroberts** [comment]
If you can provide some more context like an actual reproduction of the error in a repo, I'd be glad to help you. Your post says my app does not work with ngrx-action and RxJS 6. This is not the repo for ngrx-actions. It was not my intention to be condescending by closing the issue.

**Comment by alex-okrushko** [comment]
@gregkopp While your error might be legitimate, I think jerk move is to demand that your code should be thoroughly checked and being rude when the first suggestion was provided.
Instead if you answered like "Hm, I don't think it's related to ngrx-actions, because it doesn't even get to ofAction line. Meanwhile here is a link to a repro" - that would've been setting a nice dialog.

btw, `catchError` should be within `mergeMap` block. see https://stackoverflow.com/a/47325256/1167879
