### ISSUE TITLE
Potential breaking change in `@ngrx/store` 12.5.0

### ISSUE THREAD

**Issue by nicholas-ochoa** [ngrx/platform#3173]
It appears that a small [change was made](https://github.com/ngrx/platform/commit/605fd02efa232a5c63856c3ff2798f63fd9b4ce4#diff-afddf3064502385d641f69739f74ad0ac202db642b0ed0a7eef0eb8f5e75d17b) based on pull request #3158 that changes the behavior from the previous version (12.4) with the `store.select()` types. There was no mention of this change in the CHANGELOG.md file for 12.5, however my application was broken until I rolled back to 12.4 and did some digging on what changed. 

The code I'm currently using (which works today on 12.4):
```typescript
loadPalletTypesList$ = this.store.select(fromList.selectLoadPalletTypesList);
```

Error message received after upgrading to 12.5:
```
Error: projects/go/src/app/load/services/load.service.ts:45:44 - error TS2769: No overload matches this call.
  Overload 1 of 9, '(mapFn: (state: Record<string, unknown>) => DataList): Observable<DataList>', gave the following error.
    Argument of type 'MemoizedSelector<AppState, DataList, DefaultProjectorFn<DataList>>' is not assignable to parameter of type '(state: Record<string, unknown>) => DataList'.
  Overload 2 of 9, '(key: string): Observable<unknown>', gave the following error.
    Argument of type 'MemoizedSelector<AppState, DataList, DefaultProjectorFn<DataList>>' is not assignable to parameter of type 'string'.

45   loadPalletTypesList$ = this.store.select(fromList.selectLoadPalletTypesList);
```

It's not a huge issue, but I think the change should be mentioned in the CHANGELOG.md as a potential problem.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Angular 12.5
NgRx 12.5
Node 14.17.5
TS: 4.4.4

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[X] No

**Comment by timdeschryver** [comment]
It seems like StackBlitz is acting weird, but I can't reproduce it.
Here's what I tried locally and via [TS Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBDAnmApnA3nAyjaaC+cAZlBCHAOQACAdgOZQAeA9AM65QoUBQoksGOAGNOAQxgoAYinEBXTlhQAbFEI4AaYWImKVa6HEIkylWgxbs8Pbikb94wGhKhFRQtNLmcAghm5wEYBgVAC44dihHOm58bhs7aAcnFBc3DxkYeRQAIT8AoQhZJzCaWRAAIxSYuNt7OEdnV3dsGHE0dH9iDKzvMM9Mn06ibs5svpGc6vi6gpp2cOVVGH6enDa4AF4tDKkJ3SXoAB4VnwA+AAoKYa8UbwoASmnE4Qg5+FZFtROctYlN7ba332+igxwm2QuV3BDxqCQEs3mHz0ywm3gAKkEVP8RDtgRxzp0kUtvt5fih1J1zuw2vdNqdwq0JAA6GCY8ncR61Z4I96fFE3bIAYUKTmx2hQeOgBICRK+4LJFICVMZKFpG3p1OZBSKMApjye8NeiL5GOCKAA6kEABbCnVi3F8qWEvkk00qRULZHfIUi3WU1lmzTapxq+kAAwAJOgAypCABqOBR4MwfBhvWwmZKUSsVhwbxgMDC8CvFCijoBGMW622pwR-4wK3AVhMyycFt8qkmtmWhs1mCPGUu1FulB1rYNpstjgodvIzte4dsgee4ngvtjhCN5utmeymDz1cCvv6-JGmBQWQg85gUgSNQoAAmDLwYRweFp6FisSAA)

**Comment by timdeschryver** [comment]
@bryantlikes thanks. I was able to reproduce this now.
But the same issue arises when I'm reverting back to v12.4
