### ISSUE TITLE
@ngrx/store v11 throws a compilation error

### ISSUE THREAD

**Issue by matheo** [ngrx/platform#2919]
Today I've updated `@ngrx` v11 and I got a broken library-build with this error message
(reverting to `v10 goes back to normal):
```
@my/package: ✖ Compiling TypeScript sources through NGC
@my/package: ERROR: @ngrx/store/ngrx-store.ts(224,21): Error during template compile of 'StoreModule'
@my/package:   Expression form not supported.
@my/package: @ngrx/store/ngrx-store.ts(231,15): Error during template compile of 'StoreModule'
@my/package:   Expression form not supported.
@my/package: @ngrx/store/ngrx-store.ts(257,13): Error during template compile of 'StoreModule'
@my/package:   Expression form not supported.
@my/package: @ngrx/store/ngrx-store.ts(224,21): Error during template compile of 'StoreModule'
@my/package:   Expression form not supported.
@my/package: @ngrx/store/ngrx-store.ts(231,15): Error during template compile of 'StoreModule'
@my/package:   Expression form not supported.
@my/package: @ngrx/store/ngrx-store.ts(257,13): Error during template compile of 'StoreModule'
@my/package:   Expression form not supported.
@my/package: Error: @ngrx/store/ngrx-store.ts(224,21): Error during template compile of 'StoreModule'
@my/package:   Expression form not supported.
@my/package: @ngrx/store/ngrx-store.ts(231,15): Error during template compile of 'StoreModule'
@my/package:   Expression form not supported.
@my/package: @ngrx/store/ngrx-store.ts(257,13): Error during template compile of 'StoreModule'
@my/package:   Expression form not supported.
@my/package: @ngrx/store/ngrx-store.ts(224,21): Error during template compile of 'StoreModule'
@my/package:   Expression form not supported.
@my/package: @ngrx/store/ngrx-store.ts(231,15): Error during template compile of 'StoreModule'
@my/package:   Expression form not supported.
@my/package: @ngrx/store/ngrx-store.ts(257,13): Error during template compile of 'StoreModule'
@my/package:   Expression form not supported.
@my/package:     at Object.compileSourceFiles (/my/project/node_modules/ng-packagr/src/lib/ngc/compile-source-files.ts:96:11)
``` 

## Versions of NgRx, Angular, Node, affected browser(s):

```
Angular CLI: 11.1.4
Node: 10.22.0
OS: linux x64

Angular: 11.1.2
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.4
@angular-devkit/build-angular   0.1101.4
@angular-devkit/core            11.1.4
@angular-devkit/schematics      11.1.4
@angular/cdk                    11.2.0
@angular/cli                    11.1.4
@schematics/angular             11.1.4
@schematics/update              0.1101.4
rxjs                            6.6.3
typescript                      4.1.3
```

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by timdeschryver** [comment]
Do you have a reproduction of this @matheo ?
There's also this [stack overflow question](https://stackoverflow.com/questions/66137304/ngrx-store11-0-0-error-during-template-compile-of-storemodule) that has the same problem. 
I tried to reproduce this problem at the [angular-ngrx-material-starter](https://github.com/tomastrajan/angular-ngrx-material-starter/pull/546) repo, and everything seems to work after the upgrade.

**Comment by matheo** [comment]
@timdeschryver Unfortunately nope, and my lerna setup is hard to reproduce.
But if someone else is having the issue then it might be reproducable on a NX with Angular libraries tho,
the one triggering the issue is `ng-packagr`, that's why I kept the origin of my log.

**Comment by rishi-tandon** [comment]
We faces the same issue while updating Angular and NgRx to 11. 
```
✖ Compiling TypeScript sources through NGC
ERROR: @ngrx/store/ngrx-store.ts(224,21): Error during template compile of 'StoreModule'
  Expression form not supported.
@ngrx/store/ngrx-store.ts(231,15): Error during template compile of 'StoreModule'
  Expression form not supported.
@ngrx/store/ngrx-store.ts(257,13): Error during template compile of 'StoreModule'
  Expression form not supported.
@ngrx/store/ngrx-store.ts(224,21): Error during template compile of 'StoreModule'
  Expression form not supported.
@ngrx/store/ngrx-store.ts(231,15): Error during template compile of 'StoreModule'
  Expression form not supported.
@ngrx/store/ngrx-store.ts(257,13): Error during template compile of 'StoreModule'
  Expression form not supported.
```

**Comment by bbortt** [comment]
it was me who opened the stackoverflow thread. because I didn't want to spam your repo with an issue I am pretty much sure is my fault :)
I can track down the beta-release versions of `@ngrx/store@^11.0.0` tomorrow. we can take a look at the diffs if we know between which exact versions the error occurs.

**Comment by bbortt** [comment]
so I've done some investigation. as already mentioned on [Stackoverflow](https://stackoverflow.com/questions/66137304/ngrx-store11-0-0-error-during-template-compile-of-storemodule) I've tracked the issue down to the `StoreModule#forFeature`:

`AModule`:
```ts
import { ModuleWithProviders, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { StoreModule } from '@ngrx/store';
import { EffectsModule } from '@ngrx/effects';
import { reducers } from './reducers';

export const COMPONENTS = [
  /* a, b */
];

@NgModule({
  imports: [/* ... , */ CommonModule, ReactiveFormsModule],
  declarations: COMPONENTS,
  exports: COMPONENTS
})
export class AModule {
  static forRoot(): ModuleWithProviders<RootAModule> {
    return {
      ngModule: RootAModule,
      providers: [
        /* ... */
      ]
    };
  }
}

@NgModule({
  imports: [
    AModule,
    StoreModule.forFeature('a', reducers),
    EffectsModule.forFeature([
      /* ... */
    ])
  ]
})
export class RootAModule {}
```

`reducers`:
```ts
export interface AStateData {
  a: fromA.aType;
  b: fromB.bType;
}

export const reducers = {
  a: fromA.a,
  b: fromB.b
};

// fromA
export function a(state = initialState, action: a.Actions): aType { ... }

// fromB
export function b(state = initialState, action: b.Actions): bType { ... }
```

versions and build results, `"@angular/core": "11.1.2"` in use:
* `10.1.2` build passed.
* `11.0.0-beta.0` ([diff](https://github.com/ngrx/platform/compare/10.1.2...11.0.0-beta.0)) build failes, slightly different error:
```sh
An unhandled exception occurred: Error during template compile of 'RootAModule'
  Function calls are not supported in decorators but 'StoreModule' was called.
Unexpected value 'undefined' imported by the module 'RootAModule in ...'
Error during template compile of 'AModule'
  Function calls are not supported in decorators but 'StoreModule' was called.
```
* `11.0.0-beta.1` ([diff](https://github.com/ngrx/platform/compare/11.0.0-beta.0...11.0.0-beta.1)) build passes again.
* `11.0.0-beta.2` ([diff](https://github.com/ngrx/platform/compare/11.0.0-beta.1...11.0.0-beta.2)) build failes:
```sh
An unhandled exception occurred: @ngrx/store/ngrx-store.ts(224,21): Error during template compile of 'StoreModule'
  Expression form not supported.
@ngrx/store/ngrx-store.ts(231,15): Error during template compile of 'StoreModule'
  Expression form not supported.
@ngrx/store/ngrx-store.ts(257,13): Error during template compile of 'StoreModule'
  Expression form not supported.
@ngrx/store/ngrx-store.ts(224,21): Error during template compile of 'StoreModule'
  Expression form not supported.
@ngrx/store/ngrx-store.ts(231,15): Error during template compile of 'StoreModule'
  Expression form not supported.
@ngrx/store/ngrx-store.ts(257,13): Error during template compile of 'StoreModule'
  Expression form not supported.
```
* `11.0.0-rc-0` build failes, same error.
* `11.0.0` build failes, same error.

I will take a look at the diffs now. maybe I can find something.

**Comment by bbortt** [comment]
@timdeschryver there you go: https://github.com/bbortt/ngrx-store-module-reproducible
`yarn && yarn build:lib` should do "the trick" (aka result in the error). thanks for any help!

**Comment by qirex** [comment]
I can reproduce this with another project and can confirm that this error was not appearing in 11.0.0-beta.1 . After upgrading to 11.0.0 the build is failing.

**Comment by timdeschryver** [comment]
Thanks for the reproduction @bbortt

**Comment by brandonroberts** [comment]
I'm going to bet it's probably this one, as it's the only changes made to StoreModule.forFeature

https://github.com/ngrx/platform/pull/2885

**Comment by timdeschryver** [comment]
@brandonroberts I got a fix, I'm just validating it works against the reproduction @bbortt provided

**Comment by brandonroberts** [comment]
👍🏿

**Comment by bbortt** [comment]
> @brandonroberts I got a fix, I'm just validating it works against the reproduction @bbortt provided

@timdeschryver I can approve it. many thanks.

**Comment by matheo** [comment]
@timdeschryver the fix is still unreleased :-?

**Comment by bbortt** [comment]
> @timdeschryver the fix is still unreleased :-?

saw that too this morning. any chance to get `11.0.1`? 😄

**Comment by timdeschryver** [comment]
@matheo the fix will be in v 11.0.1
