### ISSUE TITLE
Exported variable 'storeFactory' has or is using name 'SIGNAL' from external module "node_modules/@angular/core/index" but cannot be named

### ISSUE THREAD

**Issue by mebibou** [ngrx/platform#4606]
### Which @ngrx/* package(s) are the source of the bug?

signals

### Minimal reproduction of the bug/regression with instructions

See stackblitz: https://stackblitz.com/edit/github-cnwtig-dc9puf?file=projects%2Fext%2Fpackage.json,package.json,projects%2Fext%2Fsrc%2Flib%2Fext.service.ts,src%2Fmain.ts

### Expected behavior

The library should compile successfully, has it worked correctly with Angular 17.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Angular: 18.2.11
Ngrx: 18.1.1
Typescript: 5.5.2

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by mebibou** [comment]
Note: I tried with Angular 19 and signals 19 beta, and still the same issue: https://stackblitz.com/edit/github-cnwtig-f9yxjx?file=package.json,projects%2Fext%2Fsrc%2Flib%2Fext.service.ts

**Comment by williamlambert-jc** [comment]
I've encountered the same error, it's because you're exporting the `sidenavWidth` signal twice in both your `withComputed` stages. If you remove the `sidenavWidth: sidenavWidth` line in your 2nd `withComputed` the error will disappear.

It would be nice to have better erroring on this because it took us some time to track down the issue when migrating from 17 to 18 but once we knew what we were looking for it was easy to fix 👌

**Comment by markostanimirovic** [comment]
Note that `@ngrx/signals` will display a warning in development mode when you're trying to override SignalStore members:

![1](https://github.com/user-attachments/assets/8acd8146-270f-40b3-b5b5-374a16377966)

Thanks William for the hint!

After removing the redundant `sidenavWidth` from `withComputed` both warning and compilation errors will disappear. Here is the working version: https://stackblitz.com/edit/github-cnwtig-w5s9twy1?file=projects%2Fext%2Fsrc%2Flib%2Fext.service.ts,src%2Fmain.ts

**Comment by mebibou** [comment]
amazing, thanks

**Comment by eskwisit** [comment]
Ow look who's here! 

Hope you'all doing great 🙆‍♂ 

I'm not sure this is relevant but I've got the same error message when using `WithComputed` with the State that has a nested object:

```typescript
type TimeSeriesState = {
  type: TimeSeriesType;
  data: TimeSeriesData[];
  config: TimeSeriesConfig;
};

/** initialState */

export const TimeSeriesStore = signalStore( // ◀ compiler will complain here ❌ 
  withState(initialState),
  withComputed(({ type, data }) => ({
    config: computed(() => buildChartConfig({ type, data })),
  })),
);
```

It does not complain with when the config is flat:

```typescript
type TimeSeriesState = TimeSeriesConfig & {
  type: TimeSeriesType;
  data: TimeSeriesData[];
};

/** initialState */

export const TimeSeriesStore = signalStore( // ◀ compiler will complain here ✅ 
  withState(initialState),
  withComputed(({ type, data }) => ({
    config: computed(() => buildChartConfig({ type, data })),
  })),
);
```

**However**, for some reason, both compile successfully 😅
