### PR TITLE
fix: add support for TypeScript 4.8

### LINKED ISSUE #3547: [@ngrx/effects] Throws errors with typescript@4.8.2
### Minimal reproduction of the bug/regression with instructions

Install "typescript" 4.8.2 with  "@ngrx/effects" 14.3.0 using npm.

### Minimal reproduction of the bug/regression with instructions

Should not throw any errors in node_modules

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

All versions are latest.
Angular: 14,
Node: latest
OS: Windows,
Browser: Chromium,
"@ngrx/effects": "~14.3.0",
 "@ngrx/store": "~14.3.0"

### Other information

Stack trace:
```
Error: node_modules/@ngrx/effects/src/effect_decorator.d.ts:7:84 - error TS2344: Type 'T' does not satisfy the constraint 'Object'.

7 export declare function getEffectDecoratorMetadata<T>(instance: T): EffectMetadata<T>[];    
                                                                                     ~        

  node_modules/@ngrx/effects/src/effect_decorator.d.ts:7:52
    7 export declare function getEffectDecoratorMetadata<T>(instance: T): EffectMetadata<T>[];                                                         ~
    This type parameter might need an `extends Object` constraint.


Error: node_modules/@ngrx/effects/src/effects_metadata.d.ts:3:75 - error TS2344: Type 'T' does not satisfy the constraint 'Object'.

3 export declare function getSourceMetadata<T>(instance: T): EffectMetadata<T>[];
                                                                            ~

Error: node_modules/@ngrx/effects/src/models.d.ts:25:31 - error TS2344: Type 'T' does not satisfy the constraint 'Object'.

25     [key in EffectPropertyKey<T>]?: EffectConfig;
                                 ~

  node_modules/@ngrx/effects/src/models.d.ts:24:37
    24 export declare type EffectsMetadata<T> = {
                                           ~
    This type parameter might need an `extends Object` constraint.




** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


× Failed to compile.
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

### PR DESCRIPTION
**Pull request by markostanimirovic**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #3547 

## What is the new behavior?

NgRx packages work with TypeScript 4.8

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

File: modules/effects/src/effects_metadata.ts [hunk 1]
```diff
@@ -2,7 +2,9 @@ import { EffectMetadata, EffectsMetadata } from './models';
 import { getCreateEffectMetadata } from './effect_creator';
 import { getEffectDecoratorMetadata } from './effect_decorator';
 
-export function getEffectsMetadata<T>(instance: T): EffectsMetadata<T> {
+export function getEffectsMetadata<T extends Object>(
```
Comment (markostanimirovic) [inline modules/effects/src/effects_metadata.ts:5]: this may introduce a breaking change if the `getEffectsMetadata` function (that is part of the public API) is used with an argument of the wrong type

File: modules/effects/src/models.ts [hunk 2]
```diff
@@ -34,6 +34,6 @@ export interface EffectMetadata<T extends Object>
   propertyName: EffectPropertyKey<T>;
 }
 
-export type EffectsMetadata<T> = {
-  [key in EffectPropertyKey<T>]?: EffectConfig;
+export type EffectsMetadata<T extends Object> = {
```
Comment (markostanimirovic) [inline modules/effects/src/models.ts:37]: ☝️ same here

File: modules/router-store/src/router_selectors.ts [hunk 3]
```diff
@@ -13,7 +13,7 @@ export function createRouterSelector<
   return createFeatureSelector(DEFAULT_ROUTER_FEATURENAME);
 }
 
-export function getSelectors<V>(
+export function getSelectors<V extends Record<string, any>>(
```
Comment (markostanimirovic) [inline modules/router-store/src/router_selectors.ts:16]: ☝️ same here

**Review by brandonroberts — APPROVED** [review]
