### ISSUE TITLE
ngrx effects, incompatible with Typescript

### ISSUE THREAD

**Issue by pheetah** [ngrx/platform#3555]
### Minimal reproduction of the bug/regression with instructions

After I updated my Angular application to 14, I had these errors on ngrx/effects:

```ruby
Error: node_modules/@ngrx/effects/src/effect_decorator.d.ts:7:84 - error TS2344: Type 'T' does not satisfy the constraint 'Object'.

7 export declare function getEffectDecoratorMetadata<T>(instance: T): EffectMetadata<T>[];
                                                                                     ~

  node_modules/@ngrx/effects/src/effect_decorator.d.ts:7:52
    7 export declare function getEffectDecoratorMetadata<T>(instance: T): EffectMetadata<T>[];
                                                         ~
    This type parameter might need an `extends Object` constraint.


Error: node_modules/@ngrx/effects/src/effects_metadata.d.ts:3:75 - error TS2344: Type 'T' does not satisfy the constraint 'Object'.

3 export declare function getSourceMetadata<T>(instance: T): EffectMetadata<T>[];
                                                                            ~

  node_modules/@ngrx/effects/src/effects_metadata.d.ts:3:43
    3 export declare function getSourceMetadata<T>(instance: T): EffectMetadata<T>[];
                                                ~
    This type parameter might need an `extends Object` constraint.


Error: node_modules/@ngrx/effects/src/models.d.ts:25:31 - error TS2344: Type 'T' does not satisfy the constraint 'Object'.

25     [key in EffectPropertyKey<T>]?: EffectConfig;
                                 ~

  node_modules/@ngrx/effects/src/models.d.ts:24:37
    24 export declare type EffectsMetadata<T> = {
                                           ~
    This type parameter might need an `extends Object` constraint.
```

### Minimal reproduction of the bug/regression with instructions

If you just download or clone the online-repository, you will get the errors: [Stackblitz](https://stackblitz.com/edit/ngrx-seed-3qgbwa?file=package.json,src%2Fapp%2Freducers%2Fcounter.reducer.ts) after `npm install`

Other errors are application-specific. But the ones in node_modules are caused from `@ngrx-effects`.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 14.3.0
Angular: 14.2.0
TypeScript: 4.8.2
Node: 16.15.0
Browser(s): n/a
Operation System(s): n/a

### Other information

After I downgraded Typescript to 4.6.2 I had a successful build and I could run the project as expected.

### I would be willing to submit a PR to fix this issue

- [x] Yes
- [ ] No

**Comment by pheetah** [comment]
I was able to eliminate the problem just by extending generic functions like this:

```ruby
getSourceMetadata<T> -> getSourceMetadata<T extends Object>
getEffectDecoratorMetadata<T> -> getEffectDecoratorMetadata<T extends Object>
EffectsMetadata<T> -> EffectsMetadata<T extends Object>
```

and I can create a PR if you will.

**Comment by markostanimirovic** [comment]
@pheetah

Support for TypeScript 4.8 is already merged (see https://github.com/ngrx/platform/pull/3548). It will be released soon.
