### ISSUE TITLE
ngrxPush Object is possibly 'undefined' issue after upgrading to v13

### ISSUE THREAD

**Issue by polyglot-me** [ngrx/platform#3945]
### Information

Hello Team,

I recently began updating my angular monorepo created with nrwl/nx to angular v13 and I began experiencing problems with ngrxPush pipe in ngrx v13.  These problems aren't present in ngrx until version 12.5.x. Have we altered how we use ngrxPush in any way? This is the error I receive with ngrx version 13. If I decrease the ngrx to version 12, this problem doesn't occur. Only begins to occur after version 13.

```
Error: mycomponent.component.html:51:4 - error TS2322: Type 'boolean | undefined' is not assignable to type 'boolean'.

  [primLoading]="addingRecentImprovement$ | ngrxPush
  
  Error: mycomponent.component.html:17:8 - error TS2322: Type 'boolean | undefined' is not assignable to type 'boolean | null'.

17       [loading]="addingRecentImprovement$ | ngrxPush"
```

Please suggest

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [x] No

**Comment by markostanimirovic** [comment]
Hi @polyglot-me 👋 

The `ngrxPush` typing was broken before v13 ([this PR fixes it](https://github.com/ngrx/platform/pull/3127)).

The `ngrxPush` result for `Observable<T>` is `T | undefined`. This is necessary to cover the case when the `ngrxPush` pipe is used with an observable that emits the first value asynchronously - `ngrxPush` will return `undefined` in that case.

If you're using `ngrxPush` with state observables (that always emit the first value synchronously), then you can use the non-null assertion operator:

```html
<my-cmp [primLoading]="(addingRecentImprovement$ | ngrxPush)!" />
```

Or take a look at the [`*ngrxLet` directive](https://ngrx.io/guide/component/let).
