### ISSUE TITLE
An implementation cannot be declared in ambient contexts.

### ISSUE THREAD

**Issue by FilipLaurentiu** [ngrx/platform#1534]
## Minimal reproduction of the bug/regression with instructions:
Error recive when build the project:
**ERROR in node_modules/@ngrx/effects/src/actions.d.ts(4,64): error TS1183: An implementation cannot be declared in ambient contexts.**

## Expected behavior:
Compile without error

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
node: v8.12.0
ngrx/effects: 7.1.0

## I would be willing to submit a PR to fix this issue
[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by FilipLaurentiu** [comment]
No, i don't have a repository for this. 
This happen after the update from version 6 to 7.1.0

`
```
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.2.3
@angular-devkit/schematics        7.2.3
@angular/cli                      7.2.3
@angular/http                     7.0.0
@ngtools/webpack                  7.0.7
@schematics/angular               7.2.3
@schematics/update                0.12.3
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.19.1
```
`

**Comment by timdeschryver** [comment]
And what version are the NgRx packages?

**Comment by FilipLaurentiu** [comment]
After a clean install seems that error did not occur anymore. Thank you for your time :)
